name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_nodejs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Mettez à jour cette ligne pour utiliser v4

    - name: Set up Node.js
      uses: actions/setup-node@v2  # Mettez à jour cette ligne pour utiliser v2
      with:
        node-version: '14'  # Vous pouvez également mettre à jour la version Node.js si nécessaire

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Run tests
      run: npm test

  build_java:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Mettez à jour cette ligne pour utiliser v4

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

  
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always() 
      with:
        files: target/**/*.xml 
