name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_nodejs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install
      working-directory: .

    - name: Build application
      run: npm run build
      working-directory: .

    - name: Run tests
      run: npm test
      working-directory: .

  build_java:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
